= Wfc

wfc.cs is an implementation of the https://github.com/mxgmn/WaveFunctionCollapse[WaveFunctionCollapse algorithm] (OverlappingModel) for tile maps, based on the https://gridbugs.org/wave-function-collapse/[post by Grid Bugs].

Note that it's not set up for others: not well refactored, the input file being hard coded, and even uncommon format in use!

== Notes

* The OverlappingModel can be used to fill a segment, like https://www.youtube.com/watch?v=fnFj3dOKcIQ[done in Caves of Qud]
* The OverlappingModel is _really_ slow, so I'm considering using adjacency constraints, which doesn't care about local similarity.

== Running an example

It is hard coded to run the OverlappingModel with input `Example/Res/rooms.txt`.

If you're using VSCode, there's `.vscode/tasks.json`, so type _Cmd+Shift+B_ or _Ctrl+Shift+B_ to run the Example project. Or run it typing some commands:

[source,sh]
----
$ dotnet run --project Example/Example.csproj
~~ omitted ~~
=== Source map===

###.########.###
###.#####......#
#.....###......#
#.....###......#
#...............
......###......#
#.....###......#
##.######......#
##.########.####
##.########.####
##......##....##
........##......
##............##
##......##....##
##......####.###
###.########.###

FAIL
SUCCESS
=== Output: ===
#######.#####.###.###......##...###.
....###.#####.###.###.###..##...###.
....###.###.......###.###.......###.
....###.###............##..##...##..
....##...##.......##...##..##...##..
....##...##.......##.####..#########
....#######.......##.####..#########
#.#########.......##.##########...##
#.##########.###.###.##########.....
.....#######.###.###.....##..##...##
.....##...##.##..........##.......##
#######...##.##...##.........##...##
#######...##.##########.####.#######
#######...##.##########.####.#######
#....#######.###...####.........####
#....#######.###................####
.....###...........####.........####
#....###......##...####.........####
###.####......##...####.........####
###.####......#########.........####
##....##......################.###..
##....##......##....##########.###..
########............####..####.###..
########......##....####..####.###..
########......##....#########...####
#.....##............#########...####
#.............##....#########...##..
#.....###.###.###########..##...##..
......###.###.###########.......##..
#.....###.##...####..####..##.......
#.....##..##...####........##...##..
#.....##.............####..##...##.#
#.........###.######.####.########.#
......##..###.######.####.########.#
##.#####.....................##.....
##.#####..##.................##.....

             .###.###.##
          #.......###.###..
         ##............##..#
       ..##.......##...##..##.
      ...##.......##.####..####
     ######.......##.####..#####
    #######.......##.##########..
    ########.###.###.##########..
   ..#######.###.###.....##..##...
  ...##...##.##..........##.......#
  #####...##.##...##.........##...#
  #####...##.##########.####.######
 ######...##.##########.####.#######
 ....#######.###...####.........####
 ....#######.###................####
 ....###...........####.........####
 ....###......##...####.........####
 ##.####......##...####.........####
 ##.####......#########.........####
 #....##......################.###..
 #....##......##....##########.###..
 #######............####..####.###..
 #######......##....####..####.###..
  ######......##....#########...###
  ....##............#########...###
  ............##....#########...##.
   ...###.###.###########..##...##
    ..###.###.###########.......#
    ..###.##...####..####..##....
     .##..##...####........##...
      ##.............####..##..
       ...###.######.####.####
         .###.######.####.##
          .................
             ...........
----

Good. But you'll find it's slow!

== TODO

=== Adjacency model

=== Improvements

* remove entoropy and just use `totalWeight / maxTotalWeight`
* backjumping for constant performance
* seed-based output

=== Features

* add CLI
* more generic domain (currently, it only takes `Floor` and `Wall`)
