= Wfc

wfc.cs is an implementation of the https://github.com/mxgmn/WaveFunctionCollapse[WaveFunctionCollapse algorithm] (OverlappingModel) for tile maps, based on the https://gridbugs.org/wave-function-collapse/[post by Grid Bugs].

Note that it's not set up for others: not well refactored, the input file being hard coded, and even uncommon format in use!

== Notes

* The OverlappingModel can be used to fill a segment, like https://www.youtube.com/watch?v=fnFj3dOKcIQ[done in Caves of Qud]
* The OverlappingModel is _really_ slow, so I also implemented adjacency-based constraints, which doesn't care about local similarity.
** It doesn't reduce the order of the algorithm, but makes the input smaller.

== Running an example

By default, an example of the OverlappingModel with input `Example/Res/rooms.txt` is hard coded.

If you're using VSCode, there's `.vscode/tasks.json`, so type _Cmd+Shift+B_ or _Ctrl+Shift+B_ to run the Example project. Or, run it with `dotnet`:

[source,sh]
----
$ dotnet run --project Example/Example.csproj
~~ omitted ~~
=== Source map===

###.########.###
###.#####......#
#.....###......#
#.....###......#
#...............
......###......#
#.....###......#
##.######......#
##.########.####
##.########.####
##......##....##
........##......
##............##
##......##....##
##......####.###
###.########.###

FAIL
SUCCESS
=== Output: ===
#######.#####.###.###......##...###.
....###.#####.###.###.###..##...###.
....###.###.......###.###.......###.
....###.###............##..##...##..
....##...##.......##...##..##...##..
....##...##.......##.####..#########
....#######.......##.####..#########
#.#########.......##.##########...##
#.##########.###.###.##########.....
.....#######.###.###.....##..##...##
.....##...##.##..........##.......##
#######...##.##...##.........##...##
#######...##.##########.####.#######
#######...##.##########.####.#######
#....#######.###...####.........####
#....#######.###................####
.....###...........####.........####
#....###......##...####.........####
###.####......##...####.........####
###.####......#########.........####
##....##......################.###..
##....##......##....##########.###..
########............####..####.###..
########......##....####..####.###..
########......##....#########...####
#.....##............#########...####
#.............##....#########...##..
#.....###.###.###########..##...##..
......###.###.###########.......##..
#.....###.##...####..####..##.......
#.....##..##...####........##...##..
#.....##.............####..##...##.#
#.........###.######.####.########.#
......##..###.######.####.########.#
##.#####.....................##.....
##.#####..##.................##.....

             .###.###.##
          #.......###.###..
         ##............##..#
       ..##.......##...##..##.
      ...##.......##.####..####
     ######.......##.####..#####
    #######.......##.##########..
    ########.###.###.##########..
   ..#######.###.###.....##..##...
  ...##...##.##..........##.......#
  #####...##.##...##.........##...#
  #####...##.##########.####.######
 ######...##.##########.####.#######
 ....#######.###...####.........####
 ....#######.###................####
 ....###...........####.........####
 ....###......##...####.........####
 ##.####......##...####.........####
 ##.####......#########.........####
 #....##......################.###..
 #....##......##....##########.###..
 #######............####..####.###..
 #######......##....####..####.###..
  ######......##....#########...###
  ....##............#########...###
  ............##....#########...##.
   ...###.###.###########..##...##
    ..###.###.###########.......#
    ..###.##...####..####..##....
     .##..##...####........##...
      ##.............####..##..
       ...###.######.####.####
         .###.######.####.##
          .................
             ...........
----

Good. But you'll find it's slow!

== TODO

=== Features

* more generic domain (it only takes `Floor` and `Wall`, currently)
* CLI for examples

=== Improvements

* remove entropy and just use `totalWeight / maxTotalWeight`
* backjumping for constant performance
* seed-based output
